[project]
name = "wavey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "basemap",
    "basemap-data-hires",
    "beautifulsoup4",
    "jinja2",
    "matplotlib",
    "mpld3",
    "numpy",
    "pillow",
    "pygrib",
    "requests",
    "tqdm",
    "tyro",
]

[dependency-groups]
dev = [
    "mypy",
    "pre-commit",
    "ruff",
    "types-requests",
    "types-tqdm",
]

[[tool.mypy.overrides]]
module = [
    "mpl_toolkits.basemap",
    "mpld3",
    "pygrib",
]
ignore_missing_imports = true

[tool.ruff]
line-length = 120
